spring:
  application:
    name: parser

parser:
  poll-interval: 5m
  search-urls: ${SEARCH_URLS}
  telegram:
    bot-token: ${BOT_TOKEN}
    chat-id: ${CHAT_ID}
  proxy:
    source-url: "https://api.proxyscrape.com/v4/free-proxy-list/get?request=displayproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all&limit=100"
    refresh-interval: 30m
